# Generated by Django 6.1 on 2026-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customerpayment_customertransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partially_paid', 'نیمه پرداخت'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20),
        ),
    ]
