# Generated by Django 6.1 on 2026-08-31 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transactions', to='sales.customertransaction'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('payment', 'پرداخت'), ('refund', 'برگشت وجه'), ('adjustment', 'اصلاح حساب'), ('reversal', 'معکوس')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customertransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='unique_customer_transaction_reversal'),
        ),
    ]
