# Generated by Django 6.1 on 2026-09-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customertransaction_reverses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer'),
        ),
    ]
