# Generated by Django 6.1 on 2026-08-31 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='purchases.purchaseitem'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_transaction_quantity_not_zero'),
        ),
    ]
