# Generated by Django 6.1 on 2026-08-31 19:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_order_item_ingredient'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='current_inventory_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='ingredient_stock_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('current_inventory_value__gte', 0)), name='ingredient_inventory_value_gte_zero'),
        ),
    ]
