# Generated by Django 6.1 on 2026-08-31 19:24

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ingredient_current_inventory_value_and_more'),
        ('organizations', '0001_initial'),
        ('purchases', '0002_supplierpayment_suppliertransaction_and_more'),
        ('sales', '0002_customerpayment_customertransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_transaction_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='inventory_transaction_total_cost_gte_zero'),
        ),
    ]
