# Generated by Django 6.1 on 2026-08-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorytransaction_total_cost_and_more'),
        ('organizations', '0001_initial'),
        ('purchases', '0002_supplierpayment_suppliertransaction_and_more'),
        ('sales', '0003_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transactions', to='inventory.inventorytransaction'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'خرید'), ('order_usage', 'مصرف سفارش'), ('waste', 'دورریز'), ('adjustment', 'اصلاح موجودی'), ('reversal', 'معکوس')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='unique_inventory_transaction_reversal'),
        ),
    ]
