# Generated by Django 6.1 on 2026-09-01 09:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorytransaction_reverses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
    ]
