# Generated by Django 6.1 on 2026-08-31 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('purchases', '0002_supplierpayment_suppliertransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transactions', to='purchases.suppliertransaction'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'خرید'), ('payment', 'پرداخت'), ('refund', 'برگشت خرید'), ('adjustment', 'اصلاح حساب'), ('reversal', 'معکوس')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='suppliertransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='unique_supplier_transaction_reversal'),
        ),
    ]
