# Generated by Django 6.1 on 2026-08-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_suppliertransaction_reverses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('completed', 'ثبت شده'), ('cancelled', 'لغو شده')], default='completed', max_length=20),
        ),
    ]
