# Generated by Django 6.1 on 2026-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
    ]
